namespace: cd60
name: nce
version: 0.2.2
readme: README.md
authors:
  - Benoit Ferre <benoit@example.com>
license: MIT
description: Ansible collection for Huawei iMaster NCE-Campus (tenant view). Token auth, Sites & Devices, lookup & inventory.


build_ignore:
  - tools/**
  - bundle.txt